/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class anran_hdcode2_NativeBridge */

#ifndef _Included_anran_hdcode2_NativeBridge
#define _Included_anran_hdcode2_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     anran_hdcode2_NativeBridge
 * Method:    decodeblock
 * Signature: (IIIIIIIIIIII[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_anran_hdcode2_NativeBridge_decodeblock
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jbyteArray, jintArray);

/*
 * Class:     anran_hdcode2_NativeBridge
 * Method:    test
 * Signature: (IIIIIIIIIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_anran_hdcode2_NativeBridge_test
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     anran_hdcode2_NativeBridge
 * Method:    startdecode
 * Signature: (IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_anran_hdcode2_NativeBridge_startdecode
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     anran_hdcode2_NativeBridge
 * Method:    pushdata
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_anran_hdcode2_NativeBridge_pushdata
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     anran_hdcode2_NativeBridge
 * Method:    pulldata
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_anran_hdcode2_NativeBridge_pulldata
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     anran_hdcode2_NativeBridge
 * Method:    pulldataRAW
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_anran_hdcode2_NativeBridge_pulldataRAW
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     anran_hdcode2_NativeBridge
 * Method:    releasedata
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_anran_hdcode2_NativeBridge_releasedata
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     anran_hdcode2_NativeBridge
 * Method:    getpoints
 * Signature: ([I[I)I
 */
JNIEXPORT jint JNICALL Java_anran_hdcode2_NativeBridge_getpoints
  (JNIEnv *, jclass, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
